language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer self-update
  - composer install

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit